sonar.organization=ameduza
sonar.projectKey=ameduza_typescript-project-81
sonar.projectName=typescript-project-81

sonar.sources=src,index.ts
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
